name: Flutter Web Deploy

on: push

jobs:
  hosting:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - uses: actions/checkout@v3

      # Install Dart SDK
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.4.1"

      # Install Flutter SDK
      - name: Install Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: "3.7.7"
          channel: "stable"

      # Verify Flutter and Dart SDK versions
      - name: Verify Flutter and Dart SDK versions
        run: |
          flutter --version
          dart --version

      # Clear Flutter cache
      - name: Clear Flutter cache
        run: flutter clean

      # Build Website
      - name: Build Website
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release
        working-directory: ./

      # Deploy Firebase Hosting
      - name: Deploy Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:tap-to-earn-614eb
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./
